---
# tasks file for sbaerlocher.veeam-agent



- name: Install veeam-rm
  ansible.builtin.apt:
    deb: https://repository.veeam.com/backup/linux/agent/dpkg/debian/public/pool/veeam/v/veeam-release-deb/veeam-release-deb_1.0.9_amd64.deb
    state: present

- name: Install veeam
  ansible.builtin.apt:
    name:
      - veeam
      - blksnap
    update_cache: true
  tags:
    - packages

- name: Accept eula
  ansible.builtin.command: veeamconfig agreement accepteula && veeamconfig agreement acceptthirdpartylicenses

# Veeam Backup & Replication
- when: veeam.vbrserver.name is defined
  tags:
    - configuration

  # Veeam local
  block:
    - name: Check if veeam B&R exist
      ansible.builtin.command: veeamconfig vbrserver list
      register: veeam_vbrserver_list

    - name: Create veeam B&R
      ansible.builtin.command: >-
        veeamconfig vbrserver add
        --name {{ veeam.vbrserver.name }}
        --address {{ veeam.vbrserver.endpoint }}
        --login {{ veeam.vbrserver.login }}
        --domain {{ veeam.vbrserver.domain }}
        --password {{ veeam.vbrserver.password }}
      register: veeam_create_repository
      when: veeam.vbrserver not in veeam_vbrserver_list.stdout

- when: veeam.repo.name is defined
  tags:
    - configuration

  block:
    - name: Check if veeam repo exist
      ansible.builtin.command: veeamconfig repository list
      register: veeam_repository_list

    - name: Create veeam repo
      ansible.builtin.command: veeamconfig repository create --name {{ veeam.repo.name }} --location {{ veeam.repo.path }}
      register: veeam_create_repository
      when: veeam.repo.name not in veeam_repository_list.stdout

- when: veeam.job.name is defined
  tags:
    - configuration
  block:
    - name: Load repository list
      ansible.builtin.command: veeamconfig repository list
      register: veeam_repository_list

    - name: Load veeam repository name
      ansible.builtin.set_fact:
        veeam_repository_name: "{{ veeam_repository_list.stdout_lines.1.split(' ').0 | string }}"

    - name: Check if veeam job exist
      ansible.builtin.command: veeamconfig job list
      when: ansible_os_family == 'Linux'
      register: veeam_job_list

    - name: Create veeam job
      ansible.builtin.command: veeamconfig job create --name {{ veeam.job.name }} --repoName {{  }} --maxPoints {{ veeam.job.restopoints }} --backupallsystem
      register: veeam_create_job
      when: veeam.job.name not in veeam_job_list.stdout

    - name: Load veeam job info
      ansible.builtin.command: veeamconfig job info --name {{ veeam.job.name }}
      register: veeam_job_info

    - name: Load veeam Job id
      ansible.builtin.set_fact:
        veeam_job_id: "{{ veeam_job_info.stdout_lines.1 | regex_replace('   ID: ', '') | string }}"

    - name: Check if veeam schedule exist
      ansible.builtin.shell: veeamconfig schedule show --jobId '{{ veeam_job_id }}' 2>/dev/null
      register: veeam_schedule_show
      ignore_errors: true

    - name: Create veeam schedule
      ansible.builtin.command: veeamconfig schedule set --jobId {{ veeam_job_id }} --at {{ veeam.job.at | default('20:00') }} --daily
      when: "'Run automatically: enabled' not in veeam_schedule_show.stdout"
