---
# handlers file for sbaerlocher.veeam-agent

- name: Restart veeamservices
  ansible.builtin.systemd:
    name: veeamservices
    state: restarted

- name: Enable veeamservices
  ansible.builtin.systemd:
    name: veeamservices
    enabled: true
